### ISSUE TITLE
Can not map stdout to a file

### ISSUE THREAD

**Issue by PatNichols** [swift-lang/swift-k#14]
I am using version 0.96 with openmpi 3.1.2, gcc 8.2.0 and  openjdk 1.6.
OS is centos-7 with intel haswell xeon processors.
When I try to run the tutorial case I get:
[pnichols@darwin-fe1 part01]$ swift p1.swift
Swift trunk git-rev: 58636158932dac40d09acbce76b3ae9a06190f75 heads/master 6751
RunID: run008
Progress: Fri, 07 Dec 2018 15:45:40-0700
Execution failed:
	Exception in simulation:
    Host: localhost
    Directory: p1-run008/jobs/s/simulation-hgx1i10o-0
	exception @ swift-int-staging.k, line: 187
	providerStaging:execute2 @ swift.k, line: 126
	executeSelect @ swift.k, line: 193
Caused by: Cannot find executable simulate on site system path
	exception @ swift-int-staging.k, line: 182
Caused by: null
Caused by: org.globus.cog.abstraction.impl.common.execution.JobException: Job failed with an exit code of 254
	k:assign @ swift.k, line: 157
	swift:execute @ p1, line: 31
	simulation @ p1, line: 9

It seems that the mappring between stdout and sim.out is not occurring.
Thank you for any advice you can give me on this.
Pat

**Comment by j-woz** [comment]
Looks like the simulate job could not run at all- are you sure your job is configured correctly?

**Comment by PatNichols** [comment]
The job is being launched using the swift.conf in the tutorial, part001. I
am using slurm to get an exclusive node with slurm. Then launching it as
stated in the tutorial. Perhaps there is something not stated in the
tutorial ( I did do the follow the steps and did an initial source) ? It is
running and creating a bad symlink.
Thanks,
Pat

**Comment by j-woz** [comment]
What do you mean by a bad symlink?
